version = "1.0"

[main]
name = "My Webapp Configuration"

[main.mode]
type = "select"
ask.en = "Application Mode"
ask.fr = "Mode de l'application"
help.en = "Choose the application mode. Classic: Static files + PHP. CMS: Front controller for WordPress/Drupal. CMS-Public: Front controller for Laravel/Symfony with /public folder."
help.fr = "Choisissez le mode de l'application. Classic: Fichiers statiques + PHP. CMS: Front controller pour WordPress/Drupal. CMS-Public: Front controller pour Laravel/Symfony avec dossier /public."
choices = ["classic", "cms", "cms-public"]
default = "classic"

[main.phpversion]
type = "select"
ask.en = "PHP Version"
ask.fr = "Version PHP"
help.en = "Choose the PHP version for your application"
help.fr = "Choisissez la version PHP pour votre application"
choices = ["none", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]
default = "8.4"

[main.custom_error_file]
type = "boolean"
ask.en = "Custom Error Pages"
ask.fr = "Pages d'erreur personnalisées"
help.en = "Enable custom 403/404 error pages"
help.fr = "Activer les pages d'erreur 403/404 personnalisées"
default = false

[main.with_sftp]
type = "boolean"
ask.en = "SFTP Access"
ask.fr = "Accès SFTP"
help.en = "Enable SFTP access for file management"
help.fr = "Activer l'accès SFTP pour la gestion des fichiers"
default = true

[main.password]
type = "password"
ask.en = "SFTP Password"
ask.fr = "Mot de passe SFTP"
help.en = "Password for SFTP access (leave empty to use YunoHost account password)"
help.fr = "Mot de passe pour l'accès SFTP (laissez vide pour utiliser le mot de passe de votre compte YunoHost)"
optional = true

[main.actions]
ynh_app_config_apply = "config"