version = "1.0"

[main]
name.en = "FlexWebApp configuration"
name.fr = "Configuration de FlexWebApp"

    [main.sftp]
    name.en = "SFTP access"
    name.fr = "Accès SFTP"

        [main.sftp.with_sftp]
        ask.en = "Do you need a SFTP access?"
        ask.fr = "Avez-vous besoin d'un accès SFTP ?"
        type = "boolean"
        default = true

        [main.sftp.password]
        ask.en = "Set a password for the SFTP access"
        ask.fr = "Définir un mot de passe pour l’accès SFTP"
        type = "password"
        optional = true
        visible = "with_sftp"
        help.en = "If a password already exists, leave blank and it will not be replaced. If no password exists, a random one will be generated."
        help.fr = "Si un mot de passe existe déjà, laissez vide et il ne sera pas remplacé. Si aucun mot de passe n'existe, un mot de passe aléatoire sera généré."

    [main.code_error]
    name.en = "HTML Custom error"
    name.fr = "Erreur personnalisée HTML"

        [main.code_error.custom_error_file]
        ask.en = "Activate the custom error file use"
        ask.fr = "Activer l'utilisation du fichier d'erreur personnalisé"
        type = "boolean"
        default = false
        help.en = "Once custom error enabled, you can add/create a custom `404.html` file in a directory `www\\error`."
        help.fr = "Une fois l'erreur personnalisée activée, vous pouvez ajouter/créer un fichier `404.html` personnalisé dans un répertoire `www\\error`."

    [main.php_fpm_config]
    name.en = "PHP-FPM configuration"
    name.fr = "Configuration PHP-FPM"

        [main.php_fpm_config.phpversion]
        ask.en = "PHP version"
        ask.fr = "Version PHP"
        type = "select"
        choices = ["none", "8.1", "8.2", "8.3", "8.4"]
        default = "none"

    [main.application_mode]
    name.en = "Application Mode"
    name.fr = "Mode d'Application"

        [main.application_mode.mode]
        ask.en = "Choose the application mode"
        ask.fr = "Choisissez le mode d'application"
        type = "select"
        choices = ["static", "front-controller", "framework"]
        default = "static"
        help.en = "static: Static files only, front-controller: PHP front controller at root, framework: Modern framework structure with public folder"
        help.fr = "static: Fichiers statiques uniquement, front-controller: Contrôleur frontal PHP à la racine, framework: Structure de framework moderne avec dossier public"
