packaging_format = 3

id = "my_webapp"
name = "My Webapp"
description.en = "Custom Web app with SFTP access to serve static (HTML, CSS, JS) and PHP files"
description.fr = "Application Web personnalisée avec accès SFTP pour servir des fichiers statiques (HTML, CSS, JS) et PHP"

version = "1.0~ynh21"

maintainers = []

[upstream]
license = "GPL-3.0-only"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/site"

    [install.with_sftp]
    ask.en = "Do you need a SFTP access?"
    ask.fr = "Avez-vous besoin d'un accès SFTP ?"
    type = "boolean"
    default = true

    [install.password]
    type = "password"
    optional = true
    help.en = "Optional, this corresponds to the password for SFTP access, if you enabled it"
    help.fr = "Optionnel, corresponds au mot de passe pour l'accès SFTP, si vous l'avez activé"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.php_version]
    ask.en = "Choose a PHP version you want to use for your app"
    ask.fr = "Choisissez une version PHP que vous souhaitez utiliser pour votre application"
    type = "select"
    choices = ["none", "8.1", "8.2", "8.3", "8.4"]
    default = "none"

    [install.database]
    ask.en = "Do you need a database?"
    ask.fr = "Avez-vous besoin d'une base de données ?"
    type = "select"
    choices = [ "none", "mysql", "postgresql" ]
    default = "none"

    [install.custom_error_file]
    ask.en = "Activate the custom error file use"
    ask.fr = "Activer l'utilisation du fichier d'erreur personnalisé"
    type = "boolean"
    default = false
    help.en = "Once custom error enabled, you can add/create a custom `404.html` file in a directory `www\\error`."
    help.fr = "Une fois l'erreur personnalisée activée, vous pouvez ajouter/créer un fichier `404.html` personnalisé dans un répertoire `www\\error`."

[resources]
    [resources.system_user]
    allow_sftp = "'__WITH_SFTP__' == '1'"

    [resources.install_dir]
    paths_for_www_data = ["www"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "nginx"  # Kind of "dummy" value to be sure to have a non-empty dep list

    packages_from_raw_bash = """
        if [[ "$database" == "mysql" ]]; then
            echo "mariadb-server"

            if [[ "$php_version" != none ]]; then
                echo "php${php_version}-mysql"
            fi
        elif [[ "$database" == "postgresql" ]]; then
            echo "postgresql postgresql-contrib"

            if [[ "$php_version" != none ]]; then
                echo "php${php_version}-pgsql"
            fi
        fi

        if [[ "$php_version" != none ]]; then
            echo "php${php_version}-fpm"
        fi
    """

    [resources.database]
    main.if = "'__DATABASE__' != 'none'"
    main.dbtype = "__DATABASE__"
    
[configurations]

    [configurations.nginx]

    [configurations.php]
    main.if = "'__PHP_VERSION__' != 'none'"
