packaging_format = 2

id = "flexwebapp"
name = "FlexWebApp"
description.en = "Custom Web app with SFTP access to serve static (HTML, CSS, JS) and PHP files"
description.fr = "Application Web personnalisée avec accès SFTP pour servir des fichiers statiques (HTML, CSS, JS) et PHP"

version = "1.0~ynh21"

maintainers = []

[upstream]
license = "GPL-3.0-only"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/site"

    [install.with_sftp]
    ask.en = "Do you need a SFTP access?"
    ask.fr = "Avez-vous besoin d'un accès SFTP ?"
    type = "boolean"
    default = true

    [install.password]
    type = "password"
    optional = true
    help.en = "Optional SFTP password. If left empty, a random password will be generated automatically"
    help.fr = "Mot de passe SFTP optionnel. Si laissé vide, un mot de passe aléatoire sera généré automatiquement"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.phpversion]
    ask.en = "Choose a PHP version you want to use for your app"
    ask.fr = "Choisissez une version PHP que vous souhaitez utiliser pour votre application"
    type = "select"
    choices = ["none", "8.1", "8.2", "8.3", "8.4"]
    default = "none"

    [install.database]
    ask.en = "Do you need a database?"
    ask.fr = "Avez-vous besoin d'une base de données ?"
    type = "select"
    choices = [ "none", "mysql", "postgresql" ]
    default = "none"

    [install.custom_error_file]
    ask.en = "Activate the custom error file use"
    ask.fr = "Activer l'utilisation du fichier d'erreur personnalisé"
    type = "boolean"
    default = false
    help.en = "Once custom error enabled, you can add/create a custom `404.html` file in a directory `www\\error`."
    help.fr = "Une fois l'erreur personnalisée activée, vous pouvez ajouter/créer un fichier `404.html` personnalisé dans un répertoire `www\\error`."

    [install.mode]
    ask.en = "Choose the application mode"
    ask.fr = "Choisissez le mode d'application"
    type = "select"
    choices = ["static", "front-controller", "framework"]
    default = "static"
    help.en = "static: Static files only, front-controller: PHP front controller at root, framework: Modern framework structure with public folder"
    help.fr = "static: Fichiers statiques uniquement, front-controller: Contrôleur frontal PHP à la racine, framework: Structure de framework moderne avec dossier public"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "nginx"  # Kind of "dummy" value to be sure to have a non-empty dep list
    packages_from_raw_bash = """
        if [[ "$database" == "mysql" ]]; then
            echo "mariadb-server"

            if [[ "$phpversion" != none ]]; then
                echo "php${phpversion}-mysql"
            fi
        elif [[ "$database" == "postgresql" ]]; then
            echo "postgresql postgresql-contrib"

            if [[ "$phpversion" != none ]]; then
                echo "php${phpversion}-pgsql"
            fi
        fi

        if [[ "$phpversion" != none ]]; then
            echo "php${phpversion}-fpm"
        fi
    """
