#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE THE MYSQL DATABASE
#=================================================

if [ $database != "none" ]; then
    ynh_script_progression --message="Removing the database..." --weight=2

    db_name=$(ynh_app_setting_get --app=$app --key=db_name)
    db_user=$db_name

    # Remove a database if it exists, along with the associated user
    if [ $database == "mysql" ]; then
        ynh_mysql_remove_db --db_user=$db_user --db_name=$db_name
    elif [ $database == "postgresql" ]; then
        ynh_psql_remove_db --db_user=$db_user --db_name=$db_name
    fi
fi

#=================================================
# REMOVE CRON JOB
#=================================================
use_git_sync=$(ynh_app_setting_get --app=$app --key=use_git_sync --default=0)
if [ "$use_git_sync" = "1" ]; then
    ynh_script_progression --message="Removing git sync cron job..." --weight=1
    (crontab -l -u $app 2>/dev/null | grep -v "sync_git.sh") | crontab -u $app -
fi

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=2

# Remove the dedicated NGINX config
ynh_remove_nginx_config
ynh_secure_remove --file="/etc/nginx/conf.d/$domain.d/$app.d"

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Removing PHP-FPM configuration..."

# Remove the dedicated PHP-FPM config
ynh_remove_fpm_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
